### ISSUE TITLE
[Suggestion] Do admin-only items need to be added to the repo?

### ISSUE THREAD

**Issue by ENORMOUZ** [Moulberry/NotEnoughUpdates-REPO#573]
For example, https://hypixel-skyblock.fandom.com/wiki/Anubis, does this need to be added to the repo? all the nbt data is avaliable.

**Comment by L1ghtRay** [comment]
hmm idk would be cool

**Comment by jani270** [comment]
We had that same topic a few months ago and the problem is that people will ask question about the items in the discord. Which is stupid and i dont want to deal with this. 
I would suggest to not add them.

**Comment by ENORMOUZ** [comment]
Hmm, okay
