### ISSUE TITLE
New weaponsmith items?

### ISSUE THREAD

**Issue by Strebbypatty** [Moulberry/NotEnoughUpdates-REPO#615]
New weaponsmith items

__Originally posted by @Strebbypatty in https://github.com/Moulberry/NotEnoughUpdates-REPO/pull/547__

**Comment by Strebbypatty** [comment]
Sorry mistake

**Comment by Feel65** [comment]
An issue for this? bru

**Comment by Feel65** [comment]
road to 696 momento
